CREATE DATABASE LAUNDRYMANAGMENTDB
USE LAUNDRYMANAGMENTDB;

CREATE TABLE CUSTOMERS
(
    CUSTOMERID INT PRIMARY KEY IDENTITY(1,1),
    FULLNAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ADRESS VARCHAR(150) NOT NULL
);


CREATE TABLE SERVICES
(
    SERVICEID INT PRIMARY KEY IDENTITY(1,1),
    SERVICENAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL
);

CREATE TABLE ORDERS
(
    ORDERID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMERID INT NOT NULL,
    SERVICEID INT NOT NULL,
    ORDERDATE DATE NOT NULL,
    TOTALAMOUNT DECIMAL(10,2) NOT NULL,
    STATUSS VARCHAR(50) NOT NULL,

    CONSTRAINT FK_CUSTOMER
    FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMERS(CUSTOMERID),

    CONSTRAINT FK_SERVICE
    FOREIGN KEY (SERVICEID)
    REFERENCES SERVICES(SERVICEID)
);

go

CREATE TABLE PAYMENTS
(
    PAYMENTID INT PRIMARY KEY IDENTITY(1,1),
    ORDERID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENTDATE DATE NOT NULL,
    PAYMENTMETHOD VARCHAR(30) NOT NULL,

    CONSTRAINT FK_ORDER
    FOREIGN KEY (ORDERID)
    REFERENCES ORDERS(ORDERID)
);

CREATE TABLE USERS
(
    USERID INT PRIMARY KEY IDENTITY(1,1),
    FULLNAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL
   
);

INSERT INTO USERS VALUES  (
'zackmahad' , 'zack' , '1234')

INSERT INTO USERS VALUES  (
'admin' , 'admin' , '123')



INSERT INTO CUSTOMERS
(FULLNAME, PHONE, ADRESS)
VALUES
('ZAKARIA MAHAD MOHAMOUD','0615074954','MOGADISHU'),
('FATIMA OSMAN','0611111111','HODAN')
;


INSERT INTO SERVICES
(SERVICENAME, PRICE)
VALUES
('WASHING',5),
('DRY CLEANING',10),
('IRONING',3);

INSERT INTO ORDERS
(CUSTOMERID,SERVICEID,ORDERDATE,TOTALAMOUNT,STATUSS)
VALUES
(1,1,'2026-06-17',5,'PENDING'),
(2,2,'2026-06-17',10,'READY'),
(3,3,'2026-06-17',3,'DELIVERED');



INSERT INTO PAYMENTS
(ORDERID,AMOUNT,PAYMENTDATE,PAYMENTMETHOD)
VALUES
(1,5,'2026-06-17','EVC PLUS'),
(2,10,'2026-06-17','CASH'),
(3,3,'2026-06-17','SALAAM BANK');


SELECT * FROM CUSTOMERS
SELECT * FROM SERVICES
SELECT * FROM ORDERS
SELECT * FROM PAYMENTS




